Feature#21/modif color interface
needone/pr-tricks pull request #22
Opened 2021-04-19 14:04 UTC by hugo-barbi-needone

## Capture
![image](https://user-images.githubusercontent.com/82021898/115249253-b86f5580-a128-11eb-80ce-3fa44f64b7a6.png)

## Fonctionnalité
- <input type="color"> permettant de changer la couleur du background de la page option 

## Amélioration
- Dans le futur on pourrait permettre de changer la couleur des tricks (par type par exemple) pour mieux les distingués sur un PR

2021-04-19 14:23 UTC, julien-boucly-needone requested changes

2021-04-19 14:23 UTC, julien-boucly-needone commented on src/content-script-github.ts
> +    for await (const element of elements) {
ici tu peux remplacer ton `for` par une méthode asynchrone ;) 
Jète un coup d'oeil la dessus => https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2021-04-19 14:23 UTC, julien-boucly-needone commented on src/content-script-github.ts
> +            function userPreferences(trick): void {
Transforme ta fonction en fonction ES6 :)

2021-04-19 14:23 UTC, julien-boucly-needone commented on src/options.ts
> +    }
Transforme cette fonction en fonction ES6 https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Functions/Arrow_functions

2021-04-19 14:23 UTC, julien-boucly-needone commented on src/options.ts
> +        }
idem

2021-04-19 14:23 UTC, julien-boucly-needone commented on src/options.ts
> +    }
idem

2021-04-19 14:23 UTC, julien-boucly-needone commented on src/options.ts
> +    }
bon du coup partout x)

2021-04-20 06:32 UTC, nicolas-gehringer-needone commented
Alors par contre attention ⚠️ , j'ai l'impression que tu embarques les modifs de #20 dans ta PR alors qu'elle n'a rien à voir
Je crois que tu as créé ta nouvelle branche depuis #20 et pas depuis master

2021-04-20 08:39 UTC, closed without merging