Feature#23/Pouvoir charger une trickList externe à partir d'une URL
needone/pr-tricks pull request #35
Opened 2021-05-05 13:47 UTC by hugo-barbi-needone

## Description

 - On peut maintenant charger une trickList externe à partir d'une URL
 - Les Tricks récupéré sont fusionner à la liste de Tricks par défaut et permet toujours un filtrage un mode formation
 - L'interface affiche les url actives et permet de supprimer n'importe quelle url à tout moment

## Ticket de référence

https://github.com/needone/pr-tricks/issues/34

## Captures d'écrans / Vidéos

![image](https://user-images.githubusercontent.com/82021898/117150458-7563e200-adb8-11eb-9db0-5661fd455aef.png)
---

[Rappel des conventions](https://github.com/needone/sfts-docs/wiki/Conventions-de-langue-&-autres)

2021-05-05 14:01 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +        });
Fait respirer le code 👃

2021-05-05 14:01 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +    private static _addCategories(element: string): void {
JSDOC

2021-05-05 14:02 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +                // eslint-disable-next-line no-alert
Met un eslint disable global sur ton fichier

2021-05-05 14:02 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +    private static _addURL(url: string): void {
JSDOC

2021-05-05 14:03 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +    private static _saveURLtoStorage(): void {
JSDOC

2021-05-05 14:03 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +            // eslint-disable-next-line no-alert
A supprimer donc, suite à mon autre commentaire

2021-05-05 14:04 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +            await Promise.all(
👃

2021-05-05 14:04 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +        TrickListOptions._restoreOptions();
👃

2021-05-05 14:17 UTC, hugo-barbi-needone commented on src/data/test.json
> +]
Fichier de test pour la prochaine feature

2021-05-05 14:20 UTC, hugo-barbi-needone commented on src/trick-list-options.ts
> +    private static _addURL(url: string): void {
Pas compris, tu peux préciser stp ?

2021-05-05 15:02 UTC, hugo-barbi-needone commented on src/trick-list-options.ts
> +            async (items: ChromeStorageType) => {
Je crois qu'il est utile pour le await ici
![image](https://user-images.githubusercontent.com/82021898/117163135-a990d000-adc3-11eb-9cdc-4da4351b6801.png)

2021-05-05 15:04 UTC, julien-boucly-needone requested changes

2021-05-05 15:04 UTC, julien-boucly-needone commented on public/manifest.json
> +    "https://mocki.io/v1/f2cc018a-2692-4c00-9314-a947d38ae3ee"
Trouvé une solutions pour que ça fonctionne sans ça ! 
Ont ne pourra pas avoir l'url à l'avance des api extérieur

2021-05-05 15:04 UTC, julien-boucly-needone commented on src/data/test.json
> +]
Si c'est pour la prochaine feature il ne devrait pas être dans cette pr, mais laisse le tant pis

2021-05-05 15:04 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +    private static async _init(): Promise<void> {
Async toujours inutile

2021-05-05 15:04 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +            async (items: ChromeStorageType) => {
idem

2021-05-05 15:04 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +            // eslint-disable-next-line no-alert
Toujours à supprimer

2021-05-05 15:15 UTC, hugo-barbi-needone commented on public/manifest.json
> +    "https://mocki.io/v1/f2cc018a-2692-4c00-9314-a947d38ae3ee"
Je viens de supprimer l'url du manifest et ça fonctionne

2021-05-06 08:03 UTC, julien-boucly-needone requested changes

2021-05-06 08:03 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +            async (items: ChromeStorageType) => {
Ok yes bien vu

2021-05-06 08:03 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +                // eslint-disable-next-line no-alert
Pas fait

2021-05-06 08:03 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +// eslint-disable-global
Tu dois mettre la règle eslint que tu veux disabled dans ce fichier pas toutes les règles !

2021-05-06 08:03 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +// eslint-disable-global
Utilise les raccourcie de correction automatique de VSCODE ;)

2021-05-06 08:34 UTC, julien-boucly-needone approved these changes

2021-05-06 08:35 UTC, merged