Feature/#6 Control import trick list for projects
needone/pr-tricks pull request #42
Opened 2021-05-27 08:52 UTC by hugo-barbi-needone

## Description

- Les tricks sont maintenant découpés/rangés par section (1 section = 1 project)
- Il est possible d'activer et désactiver chaque section indépendamment des autres sans supprimer l'import
- Il est possible d'ajouter un nombre illimité de trickList (Dans la limite d'espace de l'interface utilisateur encore à définir)
- Il est possible d'activer ou désactiver chaque catégories de chaque trickList importés
- Il est possible de donner un nom à chaque trickList. Néanmoins impossible de donner 2 fois le même nom et d'importer 2 url identiques

## Ticket de référence

Closes #6 

## Captures d'écrans / Vidéos

![image](https://user-images.githubusercontent.com/82021898/119795023-5b5d8100-bed8-11eb-83e1-3a58223f229d.png)
![image](https://user-images.githubusercontent.com/82021898/119795212-8e077980-bed8-11eb-9716-03a14c9fe5be.png)
![image](https://user-images.githubusercontent.com/82021898/119795346-abd4de80-bed8-11eb-95bd-79c05bb9ea7b.png)

---

[Rappel des conventions](https://github.com/needone/sfts-docs/wiki/Conventions-de-langue-&-autres)

2021-05-27 09:36 UTC, julien-boucly-needone requested changes
🔥

2021-05-27 09:36 UTC, julien-boucly-needone commented on public/views/options.html
> +            -->
À supprimer

2021-05-27 09:36 UTC, julien-boucly-needone commented on public/views/options.html
>            Exemple: afficher les if, les else, autre chose-->
Jamais de commentaire ne français

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/github-review-script.ts
>      private async _setExternalTrickList(items: ChromeStorageType, trickList: Trick[]): Promise<void> {
Le async n'a plus d'utilité ici

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +        TrickListOptions._defaultTrickList.map((element: string) => {
Le `.map(` ici est inutile si tu ne l'utilise pas pour retourner une valeur ou en tant que promise. Donc à transformer en foreach

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +                            const checkbox2 = (document.getElementById(trickID) as HTMLInputElement);
```typescript
const trick = (TrickListOptions._externalTricks)[project][name].name;

const trickID = `${project}_${trick}`;
const checkbox2 = (document.getElementById(trickID) as HTMLInputElement);
```

=> 

```typescript
const trick = (TrickListOptions._externalTricks)[project][name].name;
const trickID = `${project}_${trick}`;
const checkbox2 = (document.getElementById(trickID) as HTMLInputElement);

...
```

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +                        if (tricksNameChecked.includes(elementSection)) {
👃

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +                    if (items.extTricks.tricksNameChecked.length !== 0) {
```typescript
 if (items.extTricks.tricksNameChecked !== undefined) {
       if (items.extTricks.tricksNameChecked.length !== 0) {
            ...
       }
}
```

=> 

```typescript
 if (items.extTricks.tricksNameChecked !== undefined && items.extTricks.tricksNameChecked.length !== 0) {
     ...
}
```

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +                for (let i = 0; i < TrickListOptions._urlList.url.length; i++) {
Pourquoi avoir choisi un for ici ?

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +                        window.alert("L'url a déjà été ajouté");
Simple quote pour les string

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
>      private static _displayCategories(): void {
Je pense qu'il va falloir sortir la logique d'affichage au front et la logique interne de l'extension dans un autre fichier 🤔  (Simple remarque pas à faire dans cette PR)

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +    private static _showProjectSetion(name: string, url: string): void {
JSDOC

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +                TrickListOptions._addNewTrickInDomList(name, url, true);
👃

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +    private static _removeURL(name: string, url: string, sectionID: string, isActivated: boolean): void {
Trop de paramètre dans cette méthode ! 

Trop de paramètre = refacto en objet ! 

```typescript
private static _removeURL(name: string, url: string, sectionID: string, isActivated: boolean): void {}
```

=> 

```typescript
    private static _removeURL(params: {
        name: string; 
        url: string; 
        sectionID: string; 
        isActivated: boolean;
    }): void {}
```

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +        }
Oula ? 8 ? Pourquoi ? Dangereux les while !!

2021-05-27 09:36 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +    private static _removeTrickList(section: string): void {
JSDOC

2021-05-27 09:59 UTC, hugo-barbi-needone commented on src/trick-list-options.ts
> +        }
8 c'est la taille par défault de la TrickList sans les import

2021-05-27 10:06 UTC, julien-boucly-needone requested changes
Il reste des commentaires

2021-05-27 10:06 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +                        if (tricksNameChecked.includes(elementSection)) {
Fait respirer ton code => 👃

2021-05-27 10:06 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +                    if (items.extTricks.tricksNameChecked.length !== 0) {
Pas fait

2021-05-27 10:21 UTC, hugo-barbi-needone commented on src/trick-list-options.ts
> +                for (let i = 0; i < TrickListOptions._urlList.url.length; i++) {
Pour pouvoir récupérer plus facilement chaque propriétés de urlList par rapport au même index et à la même instance

2021-05-27 10:24 UTC, hugo-barbi-needone commented on src/trick-list-options.ts
>      private static _displayCategories(): void {
Oui Nicolas m'a dis la même chose, j'ai déjà créer le ticket refracto dans le backlog.

2021-05-27 11:52 UTC, julien-boucly-needone requested changes

2021-05-27 11:52 UTC, julien-boucly-needone commented on src/trick-list-options.ts
> +                for (let i = 0; i < TrickListOptions._urlList.url.length; i++) {
Alors tu peux utiliser un foreach ;)

2021-05-28 07:39 UTC, nicolas-fersing-needone approved these changes

2021-05-28 07:39 UTC, nicolas-fersing-needone commented on src/types/url-tricks.type.ts
> +};
Il vaut mieux que urlTricks soit une liste de urlTrick:

`export type urlTrick = {
name: string;
url: string;
isActivated: boolean;
};`

Et du coup tu as dans le code des listes d'urlTrick :
`let urlTricks:urlTrick[] = [];`

Ca te permet d'éviter d'avoir un index à chaque fois que tu gères cette liste car maintenant tu as 1 objet qui a tout.
Et si tu supprimes, tu n'as qu'à supprimer 1 objet d'une liste et non 3 dans 3 listes différentes.

2021-05-28 07:39 UTC, nicolas-fersing-needone commented on src/trick-list-options.ts
> +        }
Est ce que c'est pas plus facile de faire un TrickList = defautTrickList (je sais pas le nom de la liste par defaut) ?
Ou alors TrickList est la liste par defaut qui se voit ajouter des éléments ?

2021-05-28 07:39 UTC, nicolas-fersing-needone commented on src/trick-list-options.ts
> +        }
array.length=8; 
semble plus élégant.

2021-05-28 07:40 UTC, nicolas-fersing-needone commented on src/types/url-tricks.type.ts
> +};
Possible de faire durant le refacto qui est prévu juste après

2021-05-28 08:16 UTC, merged